routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::get('/reports/fans', 'Admin\ReportsController@fans');
    Route::get('/reports/engagements', 'Admin\ReportsController@engagements');
    Route::get('/reports/reactions', 'Admin\ReportsController@reactions');
    Route::get('/reports/comments', 'Admin\ReportsController@comments');
    Route::get('/reports/shares', 'Admin\ReportsController@shares');

    Route::get('/grafics/index', 'Admin\GraficsController@index');

    /*Graficos alunos*/
    Route::get('/grafics/classturma', 'Admin\GraficsController@classTurma');
    Route::get('/grafics/classunidade', 'Admin\GraficsController@classUnidade');
    Route::get('/grafics/classgeral', 'Admin\GraficsController@classGeral');
    Route::get('/grafics/notas-aluno', 'Admin\GraficsController@notasAluno');
    Route::get('/grafics/questoes-gerais', 'Admin\GraficsController@questoesGerais');
    Route::get('/grafics/questoes-especificas', 'Admin\GraficsController@questoesEspecificas');
    Route::get('/grafics/acertos-porcentagem-Aluno', 'Admin\GraficsController@acertosPorcentagemAluno');

    /*Graficos professor*/
    Route::get('/grafics/notas-turmas', 'Admin\GraficsController@notasTurmas');

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('historics', 'Admin\HistoricController');

    Route::resource('engagements', 'Admin\EngagementsController');
    Route::post('engagements_mass_destroy', ['uses' => 'Admin\EngagementsController@massDestroy', 'as' => 'engagements.mass_destroy']);
    Route::post('engagements_restore/{id}', ['uses' => 'Admin\EngagementsController@restore', 'as' => 'engagements.restore']);
    Route::delete('engagements_perma_del/{id}', ['uses' => 'Admin\EngagementsController@perma_del', 'as' => 'engagements.perma_del']);


    Route::post('csv_parse', 'Admin\CsvImportController@parse')->name('csv_parse');
    Route::post('csv_process', 'Admin\CsvImportController@process')->name('csv_process');

 
});

app/Historic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;


class Historic extends Model
{
    use SoftDeletes;

    protected $fillable = ['matricula', 'nome', 'unidade', 'turno', 'turma', 'gabarito', 'conhecimentos_especificos',
        'acertos_conhecimentos_especificos', 'porcentagem_conhecimentos_especificos', 'fundamentacao_geral', 'acertos_fundamentacao_geral',
        'porcentagem_fundamentacao_geral', 'nota_do_teste', 'total_de_acertos', 'total_porcentagem', 'class_geral', 'class_unidade', 'class_turma', 'stats_date'];
    protected $hidden = [];

    /**
     * Set attribute to date format
     * @param $input
     */
    public function setStatsDateAttribute($input)
    {
        if ($input != null && $input != '') {
            $this->attributes['stats_date'] = Carbon::createFromFormat(config('app.date_format'), $input)->format('Y-m-d');
        } else {
            $this->attributes['stats_date'] = null;
        }
    }

    /**
     * Get attribute from date format
     * @param $input
     *
     * @return string
     */
    public function getStatsDateAttribute($input)
    {
        $zeroDate = str_replace(['Y', 'm', 'd'], ['0000', '00', '00'], config('app.date_format'));
        if ($input != $zeroDate && $input != null) {
            return Carbon::createFromFormat('Y-m-d', $input)->format(config('app.date_format'));
        } else {
            return '';
        }
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setMatriculaAttribute($input)
    {
        $this->attributes['matricula'] = $input ? $input : null;
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setNomesAttribute($input)
    {
        $this->attributes['nome'] = $input ? $input : null;
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setUnidadesAttribute($input)
    {
        $this->attributes['unidade'] = $input ? $input : null;
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setTurnoAttribute($input)
    {
        $this->attributes['turno'] = $input ? $input : null;
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setTurmaAttribute($input)
    {
        $this->attributes['turma'] = $input ? $input : null;
    }

}

app/Http/Controllers/Admin/HistoricController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Historic;
use App\Http\Requests\Admin\UpdatesRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

class HistoricController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!Gate::allows('engagement_access')) {
            return abort(401);
        }

        if (request('show_deleted') == 1) {
            if (! Gate::allows('engagement_delete')) {
                return abort(401);
            }
            $historics = Historic::onlyTrashed()->get();
        } else {
            $historics = Historic::all();
        }



        return view('admin.historics.index', compact('historics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('engagement_create')) {
            return abort(401);
        }

        return view('admin.historics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request->toArray());
        if (! Gate::allows('engagement_create')) {
            return abort(401);
        }

        $historic = Historic::create($request->all());

        return redirect()->route('admin.historics.index');
    }


    public function edit($id)
    {
        if (! Gate::allows('engagement_edit')) {
            return abort(401);
        }
        $historic = Historic::findOrFail($id);

        return view('admin.historics.edit', compact('historic'));
    }

    /**
     * Update Engagement in storage.
     *
     * @param  \App\Http\Requests\UpdateEngagementsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateHistoricsRequest $request, $id)
    {
        if (! Gate::allows('engagement_edit')) {
            return abort(401);
        }
        $$historic = Historic::findOrFail($id);
        $historic->update($request->all());

        return redirect()->route('admin.historics.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Historic  $historic
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('engagement_view')) {
            return abort(401);
        }
        $historic = Historic::findOrFail($id);

        return view('admin.historics.show', compact('historic'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Historic  $historic
     * @return \Illuminate\Http\Response
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('engagement_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Historic::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

    /**
     * Restore Engagement from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('engagement_delete')) {
            return abort(401);
        }
        $historic = Historic::onlyTrashed()->findOrFail($id);
        $historic->restore();

        return redirect()->route('admin.historics.index');
    }

    /**
     * Permanently delete Engagement from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('engagement_delete')) {
            return abort(401);
        }
        $historic = Historic::onlyTrashed()->findOrFail($id);
        $historic->forceDelete();

        return redirect()->route('admin.historics.index');
    }

}

resources/views/admin/historics/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.engagements.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.engagements.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('stats_date', trans('global.engagements.fields.stats-date').'', ['class' => 'control-label']) !!}
                    {!! Form::text('stats_date', old('stats_date'), ['class' => 'form-control date', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('stats_date'))
                        <p class="help-block">
                            {{ $errors->first('stats_date') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('fans', trans('global.engagements.fields.fans').'', ['class' => 'control-label']) !!}
                    {!! Form::number('fans', old('fans'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('fans'))
                        <p class="help-block">
                            {{ $errors->first('fans') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('engagements', trans('global.engagements.fields.engagements').'', ['class' => 'control-label']) !!}
                    {!! Form::number('engagements', old('engagements'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('engagements'))
                        <p class="help-block">
                            {{ $errors->first('engagements') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('reactions', trans('global.engagements.fields.reactions').'', ['class' => 'control-label']) !!}
                    {!! Form::number('reactions', old('reactions'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('reactions'))
                        <p class="help-block">
                            {{ $errors->first('reactions') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('comments', trans('global.engagements.fields.comments').'', ['class' => 'control-label']) !!}
                    {!! Form::number('comments', old('comments'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('comments'))
                        <p class="help-block">
                            {{ $errors->first('comments') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('shares', trans('global.engagements.fields.shares').'', ['class' => 'control-label']) !!}
                    {!! Form::number('shares', old('shares'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('shares'))
                        <p class="help-block">
                            {{ $errors->first('shares') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script src="{{ url('adminlte/plugins/datetimepicker/moment-with-locales.min.js') }}"></script>
    <script src="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $(function(){
            moment.updateLocale('{{ App::getLocale() }}', {
                week: { dow: 1 } // Monday is the first day of the week
            });
            
            $('.date').datetimepicker({
                format: "{{ config('app.date_format_moment') }}",
                locale: "{{ App::getLocale() }}",
            });
            
        });
    </script>
            
@stop

resources/views/admin/historics/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.engagements.title')</h3>
    
    {!! Form::model($engagement, ['method' => 'PUT', 'route' => ['admin.engagements.update', $engagement->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('stats_date', trans('global.engagements.fields.stats-date').'', ['class' => 'control-label']) !!}
                    {!! Form::text('stats_date', old('stats_date'), ['class' => 'form-control date', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('stats_date'))
                        <p class="help-block">
                            {{ $errors->first('stats_date') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('fans', trans('global.engagements.fields.fans').'', ['class' => 'control-label']) !!}
                    {!! Form::number('fans', old('fans'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('fans'))
                        <p class="help-block">
                            {{ $errors->first('fans') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('engagements', trans('global.engagements.fields.engagements').'', ['class' => 'control-label']) !!}
                    {!! Form::number('engagements', old('engagements'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('engagements'))
                        <p class="help-block">
                            {{ $errors->first('engagements') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('reactions', trans('global.engagements.fields.reactions').'', ['class' => 'control-label']) !!}
                    {!! Form::number('reactions', old('reactions'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('reactions'))
                        <p class="help-block">
                            {{ $errors->first('reactions') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('comments', trans('global.engagements.fields.comments').'', ['class' => 'control-label']) !!}
                    {!! Form::number('comments', old('comments'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('comments'))
                        <p class="help-block">
                            {{ $errors->first('comments') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('shares', trans('global.engagements.fields.shares').'', ['class' => 'control-label']) !!}
                    {!! Form::number('shares', old('shares'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('shares'))
                        <p class="help-block">
                            {{ $errors->first('shares') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script src="{{ url('adminlte/plugins/datetimepicker/moment-with-locales.min.js') }}"></script>
    <script src="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $(function(){
            moment.updateLocale('{{ App::getLocale() }}', {
                week: { dow: 1 } // Monday is the first day of the week
            });
            
            $('.date').datetimepicker({
                format: "{{ config('app.date_format_moment') }}",
                locale: "{{ App::getLocale() }}",
            });
            
        });
    </script>
            
@stop

resources/views/admin/historics/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.historics.title')</h3>
    @can('engagement_create')
    <p>
        <a href="{{ route('admin.engagements.create') }}" class="btn btn-success">@lang('global.app_add_new')</a>
        <a href="#" class="btn btn-warning" style="margin-left:5px;" data-toggle="modal" data-target="#myModal">@lang('global.app_csvImport')</a>
        @include('csvImport.modal', ['model' => 'Historic'])
        
    </p>
    @endcan

    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.engagements.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('global.app_all')</a></li> |
            <li><a href="{{ route('admin.engagements.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('global.app_trash')</a></li>
        </ul>
    </p>
    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($historics) > 0 ? 'datatable' : '' }} @can('engagement_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('engagement_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('global.historics.fields.stats-date')</th>
                        <th>@lang('global.historics.fields.nome')</th>
                        <th>@lang('global.historics.fields.user_matricula')</th>
                        <th>@lang('global.historics.fields.unidade')</th>
                        <th>@lang('global.historics.fields.turno')</th>
                        <th>@lang('global.historics.fields.turma')</th>
                        <th>@lang('global.historics.fields.gabarito')</th>
{{--                        <th>@lang('global.historics.fields.conhecimentos_especificos')</th>--}}
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($historics) > 0)
                        @foreach ($historics as $historic)
                            <tr data-entry-id="{{ $historic->id }}">
                                @can('engagement_delete')
                                    @if ( request('show_deleted') != 1 )<td></td>@endif
                                @endcan

                                <td field-key='stats_date'>{{ $historic->stats_date }}</td>
                                <td field-key='nome'>{{ $historic->nome }}</td>
                                <td field-key='user_matricula'>{{ $historic->matricula }}</td>
                                <td field-key='unidade'>{{ $historic->unidade }}</td>
                                <td field-key='turno'>{{ $historic->turno }}</td>
                                <td field-key='turma'>{{ $historic->turma }}</td>
                                <td field-key='gabarito'>{{ $historic->gabarito }}</td>
{{--                                <td field-key='conhecimentos_especificos'>{{ $historic->conhecimentos_especificos }}</td>--}}
                                @if( request('show_deleted') == 1 )
                                <td>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.engagements.restore', $historic->id])) !!}
                                    {!! Form::submit(trans('global.app_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.engagements.perma_del', $historic->id])) !!}
                                    {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                                                </td>
                                @else
                                <td>
                                    @can('engagement_view')
                                    <a href="{{ route('admin.engagements.show',[$historic->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('engagement_edit')
                                    <a href="{{ route('admin.engagements.edit',[$historic->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('engagement_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.engagements.destroy', $historic->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="11">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('engagement_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.engagements.mass_destroy') }}'; @endif
        @endcan

    </script>
@endsection

resources/views/admin/historics/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.engagements.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('global.engagements.fields.stats-date')</th>
                            <td field-key='stats_date'>{{ $engagement->stats_date }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.engagements.fields.fans')</th>
                            <td field-key='fans'>{{ $engagement->fans }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.engagements.fields.engagements')</th>
                            <td field-key='engagements'>{{ $engagement->engagements }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.engagements.fields.reactions')</th>
                            <td field-key='reactions'>{{ $engagement->reactions }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.engagements.fields.comments')</th>
                            <td field-key='comments'>{{ $engagement->comments }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.engagements.fields.shares')</th>
                            <td field-key='shares'>{{ $engagement->shares }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.engagements.index') }}" class="btn btn-default">@lang('global.app_back_to_list')</a>
        </div>
    </div>
@stop