routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::get('/reports/fans', 'Admin\ReportsController@fans');
    Route::get('/reports/engagements', 'Admin\ReportsController@engagements');
    Route::get('/reports/reactions', 'Admin\ReportsController@reactions');
    Route::get('/reports/comments', 'Admin\ReportsController@comments');
    Route::get('/reports/shares', 'Admin\ReportsController@shares');

    Route::get('/grafics/index', 'Admin\GraficsController@index');

    /*Graficos alunos*/
    Route::get('/grafics/classturma', 'Admin\GraficsController@classTurma');
    Route::get('/grafics/classunidade', 'Admin\GraficsController@classUnidade');
    Route::get('/grafics/classgeral', 'Admin\GraficsController@classGeral');
    Route::get('/grafics/notas-aluno', 'Admin\GraficsController@notasAluno');
    Route::get('/grafics/questoes-gerais', 'Admin\GraficsController@questoesGerais');
    Route::get('/grafics/questoes-especificas', 'Admin\GraficsController@questoesEspecificas');
    Route::get('/grafics/acertos-porcentagem-Aluno', 'Admin\GraficsController@acertosPorcentagemAluno');

    /*Graficos professor*/
    Route::get('/grafics/notas-turmas', 'Admin\GraficsController@notasTurmas');

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('historics', 'Admin\HistoricController');

    Route::resource('engagements', 'Admin\EngagementsController');
    Route::post('engagements_mass_destroy', ['uses' => 'Admin\EngagementsController@massDestroy', 'as' => 'engagements.mass_destroy']);
    Route::post('engagements_restore/{id}', ['uses' => 'Admin\EngagementsController@restore', 'as' => 'engagements.restore']);
    Route::delete('engagements_perma_del/{id}', ['uses' => 'Admin\EngagementsController@perma_del', 'as' => 'engagements.perma_del']);


    Route::post('csv_parse', 'Admin\CsvImportController@parse')->name('csv_parse');
    Route::post('csv_process', 'Admin\CsvImportController@process')->name('csv_process');

 
});

app/Http/Controllers/Admin/CsvImportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use SpreadsheetReader;
use Illuminate\Support\Facades\File;


class CsvImportController extends Controller
{

    public function parse(Request $request) {

        $file = $request->file('csv_file');

        $request->validate([
            'csv_file' => 'mimes:csv,txt',
        ]);

//        $extensions = array("xls","xlsx","xlm","xla","xlc","xlt","xlw");
//        $result = array($request->file('import_file')->getClientOriginalExtension());
//        if(in_array($result[0],$extensions)){
//            // Sucesso
//        }else{
//            // falha
//        }

        $path = $file->path();
        $hasHeader = $request->input('header', false) ? true : false;

        $reader = new SpreadsheetReader($path);
        $headers = $reader->current();
        $lines = [];
        $lines[] = $reader->next();
        $lines[] = $reader->next();

        $filename = str_random(10) . '.csv';

        $file->storeAs('csv_import', $filename);

        $modelName = $request->input('model', false);
        $fullModelName = "App\\" . $modelName;

        $model = new $fullModelName();
        $fillables = $model->getFillable();

        $redirect = url()->previous();

        return view('csvImport.parse_import', compact('headers', 'filename', 'fillables', 'hasHeader', 'modelName', 'lines', 'redirect'));

    }

    public function process(Request $request) {

        $filename = $request->input('filename', false);
        $path = storage_path('app/csv_import/' . $filename);

        $hasHeader = $request->input('hasHeader', false);

        $fields = $request->input('fields', false);
        $fields = array_flip(array_filter($fields));

        $modelName = $request->input('modelName', false);
        $model = "App\\" . $modelName;

        $reader = new SpreadsheetReader($path);
        $insert = [];

        foreach($reader as $key => $row) {
            if ($hasHeader && $key == 0) {
                continue;
            }

            $tmp = [];
            foreach($fields as $header => $k) {
                $tmp[$header] = $row[$k];
            }
            $insert[] = $tmp;

        }

        $for_insert = array_chunk($insert, 100);

        foreach ($for_insert as $insert_item) {
            $model::insert($insert_item);
        }

        $rows = count($insert);
        $table = str_plural($modelName);

        File::delete($path);

        $redirect = $request->input('redirect', false);
        return redirect()->to($redirect)->with('message', trans('global.app_imported_rows_to_table', ['rows' => $rows, 'table' => $table]));

    }

}

resources/views/csvImport/modal.blade.php
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">@lang('global.app_csvImport')</h4>
            </div>
            <div class="modal-body">
                <div class='row'>
                    <div class='col-md-12'>

                        <form class="form-horizontal" method="POST" action="{{ route('admin.csv_parse', ['model' => $model]) }}"
                              enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('csv_file') ? ' has-error' : '' }}">
                                <label for="csv_file"
                                       class="col-md-4 control-label">@lang('global.app_csv_file_to_import')</label>

                                <div class="col-md-6">
                                    <input id="csv_file" type="file" class="form-control" name="csv_file" required>

                                    @if ($errors->has('csv_file'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('csv_file') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="header" checked> @lang('global.app_file_contains_header_row')
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        @lang('global.app_parse_csv')
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/csvImport/parse_import.blade.php
@extends('layouts.app')

@section('content')

    <div class='row'>
        <div class='col-md-12'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('global.app_csvImport')
                </div>

                <div class="panel-body table-responsive">
                    <form class="form-horizontal" method="POST" action="{{ route('admin.csv_process') }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="filename" value="{{ $filename }}"/>
                        <input type="hidden" name="hasHeader" value="{{ $hasHeader }}"/>
                        <input type="hidden" name="modelName" value="{{ $modelName }}"/>
                        <input type="hidden" name="redirect" value="{{ $redirect }}"/>

                        <table class="table">
                            @if (isset($headers))
                                <tr>
                                    @foreach ($headers as $field)
                                        <th>{{ $field }}</th>
                                    @endforeach
                                </tr>
                            @endif
                            @if($lines)
                                @foreach ($lines as $line)
                                    <tr>
                                        @foreach ($line as $field)
                                            <td>{{ $field }}</td>
                                        @endforeach
                                    </tr>
                                @endforeach
                            @endif
                            <tr>
                                @foreach ($headers as $key => $header)
                                    <td>
                                        <select name="fields[{{ $key }}]">
                                            <option value=''>Por favor selecione...</option>
                                            @foreach ($fillables as $k => $fillable)
                                                <option value="{{ $fillable }}"
                                                        @if (strtolower($header) === strtolower($fillable)) selected @endif>{{ $fillable  }}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                @endforeach
                            </tr>
                        </table>

                        <button type="submit" class="btn btn-primary">
                            @lang('global.app_import_data')
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection